server:
  port: 7503

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: Finance Service
          uri: lb://finance-service
          predicates:
            - Path=/finance/**
          filters:
            - PrefixPath=/ecl-calculator/api/v1
            - AddResponseHeader=X-Powered-By, X-PLUG Gateway Service
            - name: CircuitBreaker
              args:
                name: studentCircuitBreaker
                fallbackUri: forward:/fallback/default
        - id: Credit Service
          uri: lb://credit-service
          predicates:
            - Path=/credit/**
          filters:
            - PrefixPath=/ecl-calculator/api/v1
            - AddResponseHeader=X-Powered-By, X-PLUG Gateway Service
            - name: CircuitBreaker
              args:
                name: studentCircuitBreaker
                fallbackUri: forward:/fallback/default
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      studentCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10

problem:
  stack-traces: never
  details: always
  advice:
    enabled: true
  exceptions:
    enabled: true
