server:
  port: 9091
spring:
  cloud:
    gateway:
      routes:
        - id: DEMO SERVICE
          uri: ${DEMO_SERVICE:http://localhost:8089}
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/api/v1
            - AddResponseHeader=X-Powered-By, Damba Gateway Service
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka